### ISSUE TITLE
Add a private class + lock icon to private channels

### ISSUE THREAD

**Issue by lynnandtonic** [andyet/face.camp#104]

**Comment by lynnandtonic** [comment]
+ different classes for DMs (person icon) and multiparty DMs (number or multi-person icon)

**Comment by lynnandtonic** [comment]
Icons to make:
- # for channels
- lock for private channels
- person for DMs
- people/number? for multi-person DMs

**Comment by lukekarrys** [comment]
@lynnandtonic do we need a `#` icon too? Or can we use text for that?

**Comment by lynnandtonic** [comment]
Oh lol yes I put `#` for channels and it read it as markdown and made it a title 😄

**Comment by lynnandtonic** [comment]
@lukekarrys I added the icons to a PR here: https://github.com/andyet/face.camp/pull/107 Let me know if/when you want me to jump in and do any styling.
